### ISSUE TITLE
The details of SVD in parameter fusion.

### ISSUE THREAD

**Issue by Wang-Z-W** [linlany/RAPF#1]
Congratulations on your awesome work accepted by ECCV 2024!
But I am confused by your decomposition of the parameter matrix as $W_{old} \rightarrow B R_{old}$. It's more like a QR-decomposition rather than a SVD as you clained in the paper.

**Comment by linlany** [comment]
QR decomposition results in an orthogonal matrix and an upper triangular matrix. In this case, I did not require the matrix to be upper triangular. Therefore, in the implementation, I used SVD decomposition and then multiplied the singular values with the right singular vectors as a whole. However, the goal here is to decompose the matrix into the same standard orthogonal basis linear space, which QR decomposition also achieves similarly.

**Comment by Wang-Z-W** [comment]
I got it! Thank you!
