### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by meijunhui1998** [linlany/RAPF#4]
The imagenet100 I downloaded is inconsistent with your data set, could you please provide the dataset set?

**Comment by linlany** [comment]
The ImageNet100 dataset I used is a subset of ImageNet1K. The dataset utilized in the code is from the Continuum library, which automatically constructs the 100-class dataset from ImageNet1K based on a given class list (class_orders/, dataset_reqs/imagenet100_classes.txt, following continual-clip). Therefore, you only need to provide the path of the standard ImageNet1K dataset to use it. A separate ImageNet100 dataset is not required.
