### ISSUE TITLE
CUB200以及其他数据集代码会开源吗

### ISSUE THREAD

**Issue by Kerwinw** [linlany/RAPF#5]
您好，目前只有在ImageNet100上运行的代码，请问在CUB200以及其他数据集上运行的代码会开源吗？

**Comment by linlany** [comment]
您好，近几周较为忙碌，其他几个数据集需要过段时间，如果需要详细结果或其他具体问题可以邮件联系

**Comment by linlany** [comment]
如果需要详细结果可以邮件

**Comment by linlany** [comment]
已经增加cifar100以及imagenet-r数据集及其配置
